title: My first jekyll website
description: My first jekyll website!
theme:
   url: https://thecode764.github.io/justthedocs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
